ALTER TABLE public.inscricoes ADD COLUMN IF NOT EXISTS streak_max INTEGER NOT NULL DEFAULT 0;
ALTER TABLE public.inscricoes ADD COLUMN IF NOT EXISTS vitorias INTEGER NOT NULL DEFAULT 0;
ALTER TABLE public.inscricoes ADD COLUMN IF NOT EXISTS derrotas INTEGER NOT NULL DEFAULT 0;

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS streak_max INTEGER NOT NULL DEFAULT 0;